// services/agora/src/components/poll/PollResultView.vue
<template>
  <div>

    <div class="headerTitle">
      What other people think about the statement
    </div>

    <div class="pollOptionList">
      <option-view :option="options.option1"
        :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 1"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option1Response * 100) / totalCount)" />
      <option-view :option="options.option2"
        :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 2"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option2Response * 100) / totalCount)" />
      <option-view v-if="options.option3 !== undefined && result.option3Response !== undefined"
        :option="options.option3" :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 3"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option3Response * 100) / totalCount)" />
      <option-view v-if="options.option4 !== undefined && result.option4Response !== undefined"
        :option="options.option4" :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 4"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option4Response * 100) / totalCount)" />
      <option-view v-if="options.option5 !== undefined && result.option5Response !== undefined"
        :option="options.option5" :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 5"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option5Response * 100) / totalCount)" />
      <option-view v-if="options.option6 !== undefined && result.option6Response !== undefined"
        :option="options.option6" :optionResponded="pollResponse !== undefined && pollResponse.optionChosen === 6"
        :optionPercentage="totalCount === 0 ? 0 : Math.round((result.option6Response * 100) / totalCount)" />
    </div>
    <div class="text-body2">
      {{ totalCount <= 1 ? `${totalCount} vote` : `${totalCount} votes` }} </div>
    </div>
</template>

<script setup lang="ts">
import OptionView from "components/poll/OptionView.vue";
import type {
  PollResult,
  PollOptions,
  PollOptionAndPseudonym,
} from "@/shared/types/zod";
import { zeroIfUndefined } from "src/utils/common";
const props = defineProps<{
  result: PollResult,
  options: PollOptions,
  pollResponse: PollOptionAndPseudonym | undefined,
}>()

const totalCount =
  props.result.option1Response +
  props.result.option2Response +
  zeroIfUndefined(props.result.option3Response) +
  zeroIfUndefined(props.result.option4Response) +
  zeroIfUndefined(props.result.option5Response) +
  zeroIfUndefined(props.result.option6Response);
</script>

<style scoped>
.pollOptionList {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.headerTitle {
  font-size: 1rem;
  padding-bottom: 0.5rem;
}
</style>

// services/front/src/components/feed/PollResultView.tsx
import { zeroIfUndefined } from "@/common/common";
import type {
    PollResult,
    PollOptions,
    PollOptionAndPseudonym,
} from "@/shared/types/zod";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Unstable_Grid2";

interface PollResultView {
    result: PollResult;
    pollResponse: PollOptionAndPseudonym | undefined;
    options: PollOptions;
}

// linkedin poll color: #2596be
// https://stackoverflow.com/a/35270047/11046178 for marginLeft usage

export function PollResultView({
    result,
    options,
    pollResponse,
}: PollResultView) {
    function getOptionView(
        option: string,
        optionPercentage: number,
        optionResponded: boolean
    ) {
        return (
            <Grid
                container
                alignItems="center"
                justifyContent="flex-start"
                direction="row"
                sx={{
                    my: 0.5,
                    px: 1,
                    py: 0.5,
                    background:
                        optionPercentage <= 50
                            ? `linear-gradient(90deg, #e6e9ec ${optionPercentage}%, #FFFFFF 0)`
                            : `linear-gradient(to right, #e6e9ec ${optionPercentage}%, #FFFFFF ${
                                  100 - optionPercentage
                              }%)`,
                }}
            >
                <Grid>
                    <Typography
                        variant="body1"
                        sx={{
                            fontWeight: "bold",
                            fontSize: 14,
                        }}
                    >
                        {optionResponded ? `${option} ✔️` : option}
                    </Typography>
                </Grid>
                <Grid marginLeft="auto">
                    <Typography
                        variant="body1"
                        sx={{ fontWeight: "bold", fontSize: 14 }}
                    >
                        {optionPercentage}%
                    </Typography>
                </Grid>
            </Grid>
        );
    }
    const totalCount =
        result.option1Response +
        result.option2Response +
        zeroIfUndefined(result.option3Response) +
        zeroIfUndefined(result.option4Response) +
        zeroIfUndefined(result.option5Response) +
        zeroIfUndefined(result.option6Response);
    return (
        <Grid
            sx={{ px: 2, py: 1 }}
            width="100%"
            container
            justifyContent="center"
            direction="column"
        >
            {getOptionView(
                options.option1,
                totalCount === 0
                    ? 0
                    : Math.round((result.option1Response * 100) / totalCount),
                pollResponse !== undefined && pollResponse.optionChosen === 1
            )}
            {getOptionView(
                options.option2,
                totalCount === 0
                    ? 0
                    : Math.round((result.option2Response * 100) / totalCount),
                pollResponse !== undefined && pollResponse.optionChosen === 2
            )}
            {options.option3 !== undefined
                ? getOptionView(
                      options.option3,
                      totalCount === 0 || result.option3Response === undefined
                          ? 0
                          : Math.round(
                                (result.option3Response * 100) / totalCount
                            ),
                      pollResponse !== undefined &&
                          pollResponse.optionChosen === 3
                  )
                : null}
            {options.option4 !== undefined
                ? getOptionView(
                      options.option4,
                      totalCount === 0 || result.option4Response === undefined
                          ? 0
                          : Math.round(
                                (result.option4Response * 100) / totalCount
                            ),

                      pollResponse !== undefined &&
                          pollResponse.optionChosen === 4
                  )
                : null}
            {options.option5 !== undefined
                ? getOptionView(
                      options.option5,
                      totalCount === 0 || result.option5Response === undefined
                          ? 0
                          : Math.round(
                                (result.option5Response * 100) / totalCount
                            ),
                      pollResponse !== undefined &&
                          pollResponse.optionChosen === 5
                  )
                : null}
            {options.option6 !== undefined
                ? getOptionView(
                      options.option6,
                      totalCount === 0 || result.option6Response === undefined
                          ? 0
                          : Math.round(
                                (result.option6Response * 100) / totalCount
                            ),

                      pollResponse !== undefined &&
                          pollResponse.optionChosen === 6
                  )
                : null}
        </Grid>
    );
}
